name: 'Merge Conflict Finder'
description: 'Check provided files and/or directories for the presence of conflict markers.'
branding:
  icon: 'git-merge'
  color: 'gray-dark'
inputs:
  includes:
    description: "Glob of files to search. Supports wildcards."
    required: false
    default: '*'
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/action.sh
      shell: bash
      env:
        INPUT_INCLUDES: ${{ inputs.includes }}
