name: 'Find Conflict Markers'

on:
  push:
  workflow_dispatch:
    inputs:
      tests_only:
        default: true
        description: Only run testing jobs
        type: boolean
      include_dir:
        default: ''
        description: Comma-separated list of directories to search
        type: string
      includes:
        default: '*.*'
        description: Comma-separated list of directories to search
        type: string

jobs:
  find_conflict_markers:
    runs-on: ubuntu-latest
    if: ${{ inputs.tests_only != 'true' }}
    name: Find merge conflicts
    steps:
      - uses: actions/checkout@v1
      - name: Merge Conflict finder
        uses: ./.github/..

  markers_not_found_test:
    runs-on: ubuntu-latest
    name: Conflict marker test (no markers found)
    steps:
      - uses: actions/checkout@v1
      - name: Merge Conflict finder
        with:
          include_dir: ${{ inputs.include_dir || '__test__' }}
          includes: ${{ inputs.includes || 'pass.md' }}
        uses: ./.github/..

  test_markers_found:
    runs-on: ubuntu-latest
    name: Conflict marker test (markers found)
    steps:
      - uses: actions/checkout@v1
      - name: Merge Conflict finder
        with:
          include_dir: ${{ inputs.include_dir || '__test__' }}
          includes: ${{ inputs.includes || 'fail.ts' }}
        uses: ./.github/..
